### ISSUE TITLE
[Feature Request] Firefox support / Webstore

### ISSUE THREAD

**Issue by Termuellinator** [victor-savinov/frame-by-frame#11]
Hey there!
I really love ImprovedTube and this sounds like another pretty neat addon. I'd love to see it support Firefox as well some time in the future :)

**Comment by victor-savinov** [comment]
![Screenshot from 2021-11-07 15-09-53](https://user-images.githubusercontent.com/56786596/140644363-7ef156b7-e8d9-4f94-a79d-ceea176e3d4f.png)

**Comment by victor-savinov** [comment]
![Screenshot from 2021-11-07 15-12-07](https://user-images.githubusercontent.com/56786596/140644410-fb7863f5-3246-418b-bcf2-350aa25487f5.png)

**Comment by Termuellinator** [comment]
wow, that was fast, thank you! :D

**Comment by victor-savinov** [comment]
@Termuellinator https://addons.mozilla.org/firefox/addon/frame-by-frame/

**Comment by Termuellinator** [comment]
Hm, the overlay panel is working fine (at least YT, YT embedded and vimeo), but the shortcuts don't. 
For YT that's not too much of an issue as there is frame-by-frame control via , and . anyway, but thats not for all sites.
The only other small issue i notice is that changed shortcuts are not shown in the panel (there they stay at 'ARROWLEFT' and 'ARROWRIGHT') but only when you click on them to change them do you see the current shortcut.

**Comment by victor-savinov** [comment]
@Termuellinator https://github.com/victor-savinov/frame-by-frame/releases/tag/v2.4.0

**Comment by Termuellinator** [comment]
That solves the issue with the shortcuts not being displayed correctly and the shortcut to hide the panel now works properly, as well.
The frame forward/backward shortcut still has no effect on at least youtube and vimeo (tried my prefered `ö` and `ä` as well as `a` and `d` and `Shift + ←` and `Shift + →` - no frame skipping at all
